### ISSUE TITLE
Please add a license to this repository

### ISSUE THREAD

**Issue by arfon** [mulander/oracle.tmbundle#11]
Hello there, we'd love to use this grammar in https://github.com/github/linguist (https://github.com/github/linguist/pull/2082) but before we can include it we need you to add a license to the repository. MIT/Apache-2 is preferred but you can read more about possible options here: http://choosealicense.com/

Thanks in advance!

**Comment by Shoelace** [comment]
it looks like the initial commit was the code from https://code.google.com/p/oracle-textmate-bundle/ which says it is "GNU GPL v2"

**Comment by arfon** [comment]
Good spot @Shoelace. We need this to be explicitly stated here though too I think.

**Comment by mulander** [comment]
License added. Sorry for making you all wait so long - I was traveling on the first half of Feb.
